tried compile with mpicc command
Currently Loaded Modules:
  1) lsf-tools/2.0                4) xalt/1.2.1   7) nsight-compute/2021.2.1     10) cmake/3.23.2                    13) glib/2.66.2
  2) hsi/5.0.2.p5                 5) DefApps      8) nsight-systems/2021.3.1.54  11) spectrum-mpi/10.4.0.3-20210112  14) libmd/1.0.3
  3) darshan-runtime/3.4.0-lite   6) gcc/9.3.0    9) cuda/11.0.3                 12) parallel-netcdf/1.12.2

loaded cuda etc. never got this to work. Last try was:

mpicc -std=c++17 \
   -L/gpfs/alpine/cli115/scratch/mpetersen/repos/miniWeather/simple_yakl_tests/cpp/build/YAKL \
   -I/gpfs/alpine/cli115/scratch/mpetersen/repos/miniWeather/simple_yakl_tests/cpp/YAKL/src \
   -I /gpfs/alpine/cli115/scratch/mpetersen/repos/miniWeather/simple_yakl_tests/cpp/YAKL/external \
   -lyakl -lm \
   -I/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/netcdf-c-4.8.1-2iqkfkn4t5yfw6kygt5q6iilwsbigwqq/lib \
   -I/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/netcdf-cxx4-4.3.1-aaaef3f55iyn7mn42y3sy65ihn2xkcwl/lib \
   -L/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/netcdf-c-4.8.1-2iqkfkn4t5yfw6kygt5q6iilwsbigwqq/lib \
   -L/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/netcdf-cxx4-4.3.1-aaaef3f55iyn7mn42y3sy65ihn2xkcwl/lib \
   -lnetcdf -lnetcdf_c++4 \
   ../miniWeather_serial.cpp

I could not get past this:
/usr/bin/ld: /tmp/ccKMsckI.o: undefined reference to symbol '_ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE@@GLIBCXX_3.4.21'
/sw/summit/gcc/9.3.0-2/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status